name = "smearFEM"
uuid = "7ba5e918-bc99-4a36-ba21-427d8c7ff9ca"
authors = ["soshalaw <soshalaweerathunge@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
