name = "smearFEM"
uuid = "4eee6b04-631b-4815-bf2d-d057f3bb7676"
authors = ["soshalaw <soshalaweerathunge@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
ConvexHulls2d = "438b5665-92b0-42e6-bc36-e4ac8449fa2d"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
ElasticArrays = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[compat]
julia = "1.6.7"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
